### ISSUE TITLE
No readings from AQI 

### ISSUE THREAD

**Issue by gromar88** [Wumfie/ESPHome-HPMA115S0-Sensor-Component#6]
The AQI for PM 2.5 and PM10.0 don't work in ESPHome 2023.8 - I can't compile code if I want to add those parameters to my code.
Please check pictures. If I comment those I see PM 2.5 and PM10 readings without any problem.
<img width="374" alt="1a" src="https://github.com/tom1422/ESPHome-HPMA115S0-Sensor-Component/assets/55233633/0d11f216-0853-488d-8e1b-7141d3320401">
<img width="449" alt="2a" src="https://github.com/tom1422/ESPHome-HPMA115S0-Sensor-Component/assets/55233633/f5d038af-6330-4de3-a32d-c26c41c9562b">

**Comment by tom1422** [comment]
Apologies, I have just realised that the release on the "Releases" section is old. (Doesn't have AQI functionality)
this should be the latest one [https://github.com/tom1422/ESPHome-HPMA115S0-Sensor-Component/archive/refs/heads/main.zip](https://github.com/tom1422/ESPHome-HPMA115S0-Sensor-Component/archive/refs/heads/main.zip). 
Let me know if that fixes it
Tom.

**Comment by gromar88** [comment]
Now it works like it should - I got AQI index readings.
<img width="358" alt="3" src="https://github.com/tom1422/ESPHome-HPMA115S0-Sensor-Component/assets/55233633/0528b500-2464-4c20-9210-95b7d1528078">
Thank You for fast respond and help. :)
